name: Unit Tests

on:
  workflow_dispatch: # Manual dispatch from the Actions tab in GitHub.
  workflow_call: # Allows this workflow to be called from other workflows.

permissions:
  packages: read   # ⬅️ Required for Gradle to fetch from GitHub Packages

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    env: # Expose secrets to Gradle
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-gradle

      - name: Run Unit Tests
        run: ./gradlew check --stacktrace
        #run: ./gradlew jvmTest --stacktrace

      - name: Upload Reports
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: Unit-Test-Reports
          path: |
            **/build/test-results/test/

      - name: Create Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Unit Test Report
          reporter: java-junit
          path: |
            **/build/test-results/test/*.xml
